package tessaridb

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"testing"
)

// The shared value corpus, run against this codec in both directions.
//
// Decoding alone does not check a codec. One that is wrong in the same way on
// both sides round-trips perfectly — mutating both halves of the i64 inversion is
// invisible to any test this repository could write about itself. The corpus is
// generated by a separate implementation written from the specification alone,
// which makes it the only external anchor available, and both directions are run
// against it.

const casesWhenWritten = 54

func corpusPath(t *testing.T, name string) string {
	t.Helper()
	if dir := os.Getenv("TESSARI_PROTOCOL_CONFORMANCE"); dir != "" {
		return filepath.Join(dir, name)
	}
	return filepath.Join("..", "tessaridb-protocol", "conformance", name)
}

// readCorpus fails rather than skipping when the corpus is absent: a suite that
// passes having found nothing to check reports coverage it does not have.
func readCorpus(t *testing.T, name string) map[string]json.RawMessage {
	t.Helper()
	path := corpusPath(t, name)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("the conformance corpus is not at %s: %v\n"+
			"check out tessaridb-protocol beside this repository, or set "+
			"TESSARI_PROTOCOL_CONFORMANCE to its conformance directory", path, err)
	}
	var corpus map[string]json.RawMessage
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("the corpus at %s is not JSON: %v", path, err)
	}
	return corpus
}

// one returns the single tag and body of a corpus notation object.
func one(t *testing.T, raw json.RawMessage) (string, json.RawMessage) {
	t.Helper()
	var object map[string]json.RawMessage
	if err := json.Unmarshal(raw, &object); err != nil {
		t.Fatalf("a corpus notation object: %v", err)
	}
	if len(object) != 1 {
		t.Fatalf("a corpus notation object carries one tag, got %d", len(object))
	}
	for tag, body := range object {
		return tag, body
	}
	return "", nil
}

func str(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatalf("expected a JSON string: %v", err)
	}
	return s
}

func num(t *testing.T, raw json.RawMessage) int64 {
	t.Helper()
	var n int64
	if err := json.Unmarshal(raw, &n); err != nil {
		t.Fatalf("expected a JSON number: %v", err)
	}
	return n
}

// The corpus writes an i64 as a STRING, so that a JSON parser reading numbers as
// doubles cannot round it on the way in — which is the same failure the protocol
// avoids by not putting one in a double in the first place.
func i64(t *testing.T, raw json.RawMessage) int64 {
	t.Helper()
	var n int64
	if err := json.Unmarshal([]byte(str(t, raw)), &n); err != nil {
		t.Fatalf("expected an integer written as a string: %v", err)
	}
	return n
}

func doubleFromBits(t *testing.T, raw json.RawMessage) float64 {
	t.Helper()
	b, err := hex.DecodeString(str(t, raw))
	if err != nil || len(b) != 8 {
		t.Fatalf("expected sixteen hex characters of float bits, got %q", str(t, raw))
	}
	var bits uint64
	for _, c := range b {
		bits = bits<<8 | uint64(c)
	}
	return math.Float64frombits(bits)
}

func bytesOf(t *testing.T, raw json.RawMessage) []byte {
	t.Helper()
	b, err := hex.DecodeString(str(t, raw))
	if err != nil {
		t.Fatalf("expected hex: %v", err)
	}
	return b
}

func valueOf(t *testing.T, raw json.RawMessage) Value {
	t.Helper()
	tag, body := one(t, raw)
	switch tag {
	case "none":
		return None{}
	case "null":
		return Null{}
	case "bool":
		var b bool
		if err := json.Unmarshal(body, &b); err != nil {
			t.Fatal(err)
		}
		return Bool{Value: b}
	case "integer":
		return Integer{Value: i64(t, body)}
	case "float_bits":
		return Float{Value: doubleFromBits(t, body)}
	case "decimal":
		var d struct {
			Mantissa string `json:"mantissa"`
			Scale    uint32 `json:"scale"`
		}
		if err := json.Unmarshal(body, &d); err != nil {
			t.Fatal(err)
		}
		m, ok := new(big.Int).SetString(d.Mantissa, 10)
		if !ok {
			t.Fatalf("a decimal mantissa: %q", d.Mantissa)
		}
		return Decimal{Mantissa: m, Scale: d.Scale}
	case "string":
		return Text{Value: str(t, body)}
	case "bytes":
		return Bytes{Value: bytesOf(t, body)}
	case "duration", "datetime":
		var d struct {
			Seconds string `json:"seconds"`
			Nanos   uint32 `json:"nanos"`
		}
		if err := json.Unmarshal(body, &d); err != nil {
			t.Fatal(err)
		}
		var seconds int64
		if err := json.Unmarshal([]byte(d.Seconds), &seconds); err != nil {
			t.Fatal(err)
		}
		if tag == "duration" {
			return Duration{Seconds: seconds, Nanos: d.Nanos}
		}
		return Datetime{Seconds: seconds, Nanos: d.Nanos}
	case "uuid":
		var u UUID
		copy(u.Value[:], bytesOf(t, body))
		return u
	case "table":
		return Table{ID: uint32(num(t, body))}
	case "record":
		var rec struct {
			Table uint32          `json:"table"`
			ID    json.RawMessage `json:"id"`
		}
		if err := json.Unmarshal(body, &rec); err != nil {
			t.Fatal(err)
		}
		return Record{Table: rec.Table, ID: recordIDOf(t, rec.ID)}
	case "array", "set":
		var items []json.RawMessage
		if err := json.Unmarshal(body, &items); err != nil {
			t.Fatal(err)
		}
		out := make([]Value, 0, len(items))
		for _, item := range items {
			out = append(out, valueOf(t, item))
		}
		if tag == "array" {
			return Array{Items: out}
		}
		return Set{Items: out}
	case "object":
		var fields map[string]json.RawMessage
		if err := json.Unmarshal(body, &fields); err != nil {
			t.Fatal(err)
		}
		out := make(map[string]Value, len(fields))
		for name, value := range fields {
			out[name] = valueOf(t, value)
		}
		return Object{Fields: out}
	case "range":
		var ends struct {
			Start json.RawMessage `json:"start"`
			End   json.RawMessage `json:"end"`
		}
		if err := json.Unmarshal(body, &ends); err != nil {
			t.Fatal(err)
		}
		return Range{Start: boundOf(t, ends.Start), End: boundOf(t, ends.End)}
	case "geometry":
		return Geometry{Shape: shapeOf(t, body)}
	case "regex":
		return Regex{Pattern: str(t, body)}
	default:
		t.Fatalf("the corpus carries a value tag this test does not translate: %q", tag)
		return nil
	}
}

func recordIDOf(t *testing.T, raw json.RawMessage) RecordID {
	t.Helper()
	tag, body := one(t, raw)
	switch tag {
	case "int":
		return IntegerID{Value: i64(t, body)}
	case "text":
		return TextID{Value: str(t, body)}
	case "uuid":
		var id UUIDID
		copy(id.Value[:], bytesOf(t, body))
		return id
	case "bytes":
		return BytesID{Value: bytesOf(t, body)}
	default:
		t.Fatalf("unknown record id tag in the corpus: %q", tag)
		return nil
	}
}

func boundOf(t *testing.T, raw json.RawMessage) Bound {
	t.Helper()
	var bare string
	if err := json.Unmarshal(raw, &bare); err == nil && bare == "unbounded" {
		return Unbounded{}
	}
	tag, body := one(t, raw)
	switch tag {
	case "unbounded":
		return Unbounded{}
	case "included":
		return Included{Value: valueOf(t, body)}
	case "excluded":
		return Excluded{Value: valueOf(t, body)}
	default:
		t.Fatalf("unknown range bound in the corpus: %q", tag)
		return nil
	}
}

func positionOf(t *testing.T, raw json.RawMessage) Position {
	t.Helper()
	var p struct {
		Lon json.RawMessage `json:"lon"`
		Lat json.RawMessage `json:"lat"`
	}
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	return Position{Lon: doubleFromBits(t, p.Lon), Lat: doubleFromBits(t, p.Lat)}
}

func positionsOf(t *testing.T, raw json.RawMessage) []Position {
	t.Helper()
	var items []json.RawMessage
	if err := json.Unmarshal(raw, &items); err != nil {
		t.Fatal(err)
	}
	out := make([]Position, 0, len(items))
	for _, item := range items {
		out = append(out, positionOf(t, item))
	}
	return out
}

func polygonOf(t *testing.T, raw json.RawMessage) Polygon {
	t.Helper()
	// The two corpora spell a polygon differently, and a client translating both
	// meets it twice. The value corpus names the two parts; the JSON corpus
	// writes GeoJSON's flat list of rings with the exterior first. Both are read,
	// because a translator that knew only one would fail a corpus for its
	// notation rather than this client for its behaviour (Q-GO-001).
	var flat []json.RawMessage
	if err := json.Unmarshal(raw, &flat); err == nil {
		if len(flat) == 0 {
			return Polygon{}
		}
		interiors := make([]Ring, 0, len(flat)-1)
		for _, ring := range flat[1:] {
			interiors = append(interiors, positionsOf(t, ring))
		}
		return Polygon{Exterior: positionsOf(t, flat[0]), Interiors: interiors}
	}
	var p struct {
		Exterior  json.RawMessage   `json:"exterior"`
		Interiors []json.RawMessage `json:"interiors"`
	}
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	rings := make([]Ring, 0, len(p.Interiors))
	for _, ring := range p.Interiors {
		rings = append(rings, positionsOf(t, ring))
	}
	return Polygon{Exterior: positionsOf(t, p.Exterior), Interiors: rings}
}

func shapeOf(t *testing.T, raw json.RawMessage) Shape {
	t.Helper()
	tag, body := one(t, raw)
	var items []json.RawMessage
	switch tag {
	case "point":
		return Point{Position: positionOf(t, body)}
	case "line":
		return Line{Positions: positionsOf(t, body)}
	case "polygon":
		return PolygonShape{Polygon: polygonOf(t, body)}
	case "multipoint":
		return MultiPoint{Positions: positionsOf(t, body)}
	case "multiline":
		if err := json.Unmarshal(body, &items); err != nil {
			t.Fatal(err)
		}
		lines := make([]Ring, 0, len(items))
		for _, item := range items {
			lines = append(lines, positionsOf(t, item))
		}
		return MultiLine{Lines: lines}
	case "multipolygon":
		if err := json.Unmarshal(body, &items); err != nil {
			t.Fatal(err)
		}
		polygons := make([]Polygon, 0, len(items))
		for _, item := range items {
			polygons = append(polygons, polygonOf(t, item))
		}
		return MultiPolygon{Polygons: polygons}
	case "collection":
		if err := json.Unmarshal(body, &items); err != nil {
			t.Fatal(err)
		}
		shapes := make([]Shape, 0, len(items))
		for _, item := range items {
			shapes = append(shapes, shapeOf(t, item))
		}
		return Collection{Geometries: shapes}
	default:
		t.Fatalf("unknown geometry kind in the corpus: %q", tag)
		return nil
	}
}

func TestEveryCorpusVectorEncodesAndDecodesExactly(t *testing.T) {
	corpus := readCorpus(t, "values-v1.json")

	var major int
	if err := json.Unmarshal(corpus["protocol_major"], &major); err != nil || major != 1 {
		t.Fatalf("this client implements a different major from the corpus: %v", major)
	}

	var cases []struct {
		Name  string          `json:"name"`
		Value json.RawMessage `json:"value"`
		Bytes string          `json:"bytes"`
	}
	if err := json.Unmarshal(corpus["cases"], &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < casesWhenWritten {
		t.Fatalf("the corpus shrank to %d cases — a suite cannot get stronger by losing vectors", len(cases))
	}

	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			want := valueOf(t, c.Value)

			// Forwards: this client must produce exactly the corpus's bytes.
			got, err := Encode(want)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if hex.EncodeToString(got) != c.Bytes {
				t.Fatalf("encode\n  got  %s\n  want %s", hex.EncodeToString(got), c.Bytes)
			}

			// Backwards: and must read the corpus's bytes to exactly the value.
			raw, err := hex.DecodeString(c.Bytes)
			if err != nil {
				t.Fatal(err)
			}
			back, err := Decode(raw)
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			if !sameValue(back, want) {
				t.Fatalf("decode\n  got  %#v\n  want %#v", back, want)
			}
		})
	}

	fmt.Printf("  conformance: %d vectors, both directions\n", len(cases))
}

func TestAValuePayloadWithTrailingBytesIsRefused(t *testing.T) {
	// A value carries no length of its own, so there is nowhere to resume from:
	// trailing bytes mean the reader and the writer disagree about the shape.
	encoded, err := Encode(Integer{Value: 1})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Decode(append(encoded, 0x00)); err == nil {
		t.Fatal("trailing bytes after a complete value must be an error")
	}
}

func TestAnUnknownTagIsAnErrorRatherThanAGuess(t *testing.T) {
	if _, err := Decode([]byte{0xfe}); err == nil {
		t.Fatal("an unknown value tag must be an error")
	}
}

func TestNanosecondsOutsideTheSubSecondRangeAreAnErrorNotAWrap(t *testing.T) {
	if _, err := Encode(Duration{Seconds: 0, Nanos: 1_000_000_000}); err == nil {
		t.Fatal("a nanosecond count at the ceiling must be refused")
	}
}
