// Package tessaridb is a client for TessariDB, written from the protocol
// specification and nothing else.
//
// It links nothing from the database's own repository, and nothing from the
// clients written for other languages: three clients that agree because one was
// transcribed from another agree about a mistake as readily as about the
// protocol. What they share is the conformance corpora, which are generated by a
// separate implementation written from the specification alone.
package tessaridb

import "math/big"

// A Value is one of the store's seventeen types.
//
// It is a sealed interface rather than a struct carrying every field, because a
// struct would let a caller read a Mantissa off a string and get a zero. The
// compiler does here what a discriminated union does elsewhere.
type Value interface{ isValue() }

// None is the absence of a field. Null is a field that is present and holds
// nothing. They are different, and Go makes the difference the easiest one in
// the protocol to lose: a nil Value is indistinguishable from an absent one and
// both print as <nil>, so neither is spelled nil here.
type None struct{}

type Null struct{}

type Bool struct{ Value bool }

// Integer is an i64. Go needs no ceremony for it — the one place this client is
// simpler than the TypeScript one, where the same value cost a runtime floor.
type Integer struct{ Value int64 }

// Float carries the bits the protocol asks for, so -0 survives and so does the
// canonical quiet NaN.
type Float struct{ Value float64 }

// Decimal is an i128 mantissa and a scale. The mantissa does not fit in any Go
// integer, so it is a big.Int — and it is written PLAIN on the wire, unlike an
// Integer, which is written with its first byte inverted. Three numeric types,
// two conventions.
type Decimal struct {
	Mantissa *big.Int
	Scale    uint32
}

type Text struct{ Value string }

type Bytes struct{ Value []byte }

// Duration is whole seconds plus nanoseconds in [0, 1e9).
//
// Deliberately not time.Duration: that type is an int64 count of nanoseconds and
// tops out near 292 years, while this one reaches as far as an i64 of seconds.
// Converting at the boundary would silently truncate exactly the values a caller
// could not have produced by accident.
type Duration struct {
	Seconds int64
	Nanos   uint32
}

// Datetime is seconds since the epoch plus nanoseconds, for the same reason.
type Datetime struct {
	Seconds int64
	Nanos   uint32
}

type UUID struct{ Value [16]byte }

type Table struct{ ID uint32 }

type Record struct {
	Table uint32
	ID    RecordID
}

type Array struct{ Items []Value }

// Object keeps its fields in a map because the protocol does not promise an
// order for them on the wire, and the query builder sorts by name where a
// rendering has to be reproducible.
type Object struct{ Fields map[string]Value }

// Set arrives as a list and is a distinct type, because the collection kind is
// part of what the store held.
type Set struct{ Items []Value }

type Range struct {
	Start Bound
	End   Bound
}

type Geometry struct{ Shape Shape }

// Regex carries the pattern's source. The server does not execute it, and a
// client must not compile it with its own engine and present the result as this
// store's semantics — Go's RE2 and the store's engine are not the same language.
type Regex struct{ Pattern string }

func (None) isValue()     {}
func (Null) isValue()     {}
func (Bool) isValue()     {}
func (Integer) isValue()  {}
func (Float) isValue()    {}
func (Decimal) isValue()  {}
func (Text) isValue()     {}
func (Bytes) isValue()    {}
func (Duration) isValue() {}
func (Datetime) isValue() {}
func (UUID) isValue()     {}
func (Table) isValue()    {}
func (Record) isValue()   {}
func (Array) isValue()    {}
func (Object) isValue()   {}
func (Set) isValue()      {}
func (Range) isValue()    {}
func (Geometry) isValue() {}
func (Regex) isValue()    {}

// A RecordID is a record's identity within its table. The four variants are
// fixed forever.
type RecordID interface{ isRecordID() }

type IntegerID struct{ Value int64 }
type TextID struct{ Value string }
type UUIDID struct{ Value [16]byte }
type BytesID struct{ Value []byte }

func (IntegerID) isRecordID() {}
func (TextID) isRecordID()    {}
func (UUIDID) isRecordID()    {}
func (BytesID) isRecordID()   {}

// A Bound is one end of a range. Either end may itself hold a range.
type Bound interface{ isBound() }

type Unbounded struct{}
type Included struct{ Value Value }
type Excluded struct{ Value Value }

func (Unbounded) isBound() {}
func (Included) isBound()  {}
func (Excluded) isBound()  {}

// Position is a point on the sphere. Longitude first, as RFC 7946 §3.1.1 fixes:
// the opposite order is the most common bug in geospatial code precisely because
// it is silent, and a point in Paris becomes a point in the Indian Ocean, which
// is a perfectly valid place. Altitude is not carried by the protocol.
type Position struct {
	Lon float64
	Lat float64
}

// Ring is a ring of positions. The codec does not require it to close.
type Ring []Position

type Polygon struct {
	Exterior  Ring
	Interiors []Ring
}

// A Shape is one of the seven geometry kinds.
type Shape interface{ isShape() }

type Point struct{ Position Position }
type Line struct{ Positions []Position }
type PolygonShape struct{ Polygon Polygon }
type MultiPoint struct{ Positions []Position }
type MultiLine struct{ Lines []Ring }
type MultiPolygon struct{ Polygons []Polygon }
type Collection struct{ Geometries []Shape }

func (Point) isShape()        {}
func (Line) isShape()         {}
func (PolygonShape) isShape() {}
func (MultiPoint) isShape()   {}
func (MultiLine) isShape()    {}
func (MultiPolygon) isShape() {}
func (Collection) isShape()   {}
